Rework backup step
ROCmSoftwarePlatform/migraphx-benchmark pull request #21
Opened 2023-04-26 09:44 UTC by pavlejacovicHTEC

In previous PR ( https://github.com/ROCmSoftwarePlatform/migraphx-benchmark/pull/20 ), there were some merge conflicts because main branch was not pulled, so we created this new PR from from scratch so everything is clean and organized. If you got notification to review that closed PR,  just ignore it and only review this one.

This PR is linked with PR's:
1. https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1719

2023-04-28 14:50 UTC, causten requested changes

2023-05-03 09:57 UTC, IgorMirosavljevicHTEC commented on .github/workflows/perf-test.yml
> +          git config --local user.name github-actions@github.com
Config typo fixed

2023-05-03 14:41 UTC, causten requested changes
merge this change in to your #20 PR.  PRs should be fully functional.  As it stands right now I would need two different PRs to be fully functional

2023-05-03 18:14 UTC, IgorMirosavljevicHTEC commented
PR#20 (to migraphx-benchmark repo) is closed due the multiple conflicts and PR#1719 (introducing additional parameter that is used in performance workflow) to AMDMIGraphX is already merged.
There are 2 PR's because trigger workflow (configuration) is part of AMDMIGraphX repo and actual workflow (action) that uses configuration from trigger is part of migraphx-benchmark repo. These two are working correctly only in tandem, merging just PR#1719 did broke all the performance runs.

2023-05-03 23:44 UTC, causten approved these changes

2023-05-03 23:44 UTC, merged